proxy:
  container_name: wisdota-proxy
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /home/fischerq/Documents/Wisdota/dota-analysis/web-server/nginx/vhosts:/etc/nginx/vhost.d:ro
postgres:
  container_name: postgres-container
  image: postgres
  expose:
    - "5432"
  environment:
    POSTGRES_USER: "wisdota"
    POSTGRES_PASSWORD: "the-database-elephant"
    PGDATA: "/postgres/data"
  volumes:
    - /home/fischerq/Documents/Wisdota/dota-analysis/web-server/storage/postgres:/postgres
webserver:
  build: webserver
  expose:
    - "42000"
  volumes:
    - /home/fischerq/Documents/Wisdota/dota-analysis/web-server/webserver/src:/source:ro
    - /home/fischerq/Documents/Wisdota/dota-analysis/web-server/storage/webserver:/storage
    - /home/fischerq/Documents/Wisdota/dota-analysis/web-server/storage/shared:/shared
    - /home/fischerq/Documents/Wisdota/dota-analysis/web-server/files/webserver:/files:ro
    - /home/fischerq/Documents/Wisdota/dota-analysis/web-server/shared-code:/shared-code:ro
  environment:
    VIRTUAL_HOST: "localhost"
    VIRTUAL_PORT: "42000"
  links:
    - postgres:POSTGRES_IP
scheduler:
  build: scheduler
  volumes:
    - /home/fischerq/Documents/Wisdota/dota-analysis/web-server/storage/scheduler:/storage
    - /home/fischerq/Documents/Wisdota/dota-analysis/web-server/storage/shared:/shared
    - /home/fischerq/Documents/Wisdota/dota-analysis/web-server/scheduler/src:/source:ro
    - /home/fischerq/Documents/Wisdota/dota-analysis/web-server/shared-code:/shared-code:ro
  links:
    - postgres:POSTGRES_IP
analysis:
  build: analysis
  volumes:
    - /home/fischerq/Documents/Wisdota/dota-analysis/web-server/analysis/server-src:/source:ro
    - /home/fischerq/Documents/Wisdota/dota-analysis/web-server/analysis/extractor:/extractor:ro
    - /home/fischerq/Documents/Wisdota/dota-analysis/web-server/analysis/analysis:/analysis:ro
    - /home/fischerq/Documents/Wisdota/dota-analysis/web-server/analysis/score:/score:ro
    - /home/fischerq/Documents/Wisdota/dota-analysis/web-server/shared-code:/shared-code:ro

    - /home/fischerq/Documents/Wisdota/dota-analysis/web-server/storage/analysis:/storage
    - /home/fischerq/Documents/Wisdota/dota-analysis/web-server/storage/shared:/shared
    - /home/fischerq/Documents/Wisdota/dota-analysis/web-server/files/analysis:/files:ro
  links:
    - postgres:POSTGRES_IP
retrieve:
  build: retrieve
  volumes:
    - /home/fischerq/Documents/Wisdota/dota-analysis/web-server/storage/retrieve:/storage
    - /home/fischerq/Documents/Wisdota/dota-analysis/web-server/storage/shared:/shared
    - /home/fischerq/Documents/Wisdota/dota-analysis/web-server/retrieve/src:/source:ro
    - /home/fischerq/Documents/Wisdota/dota-analysis/web-server/shared-code:/shared-code:ro
  links:
    - postgres:POSTGRES_IP
download:
  build: download
  volumes:
    - /home/fischerq/Documents/Wisdota/dota-analysis/web-server/storage/download:/storage
    - /home/fischerq/Documents/Wisdota/dota-analysis/web-server/storage/shared:/shared
    - /home/fischerq/Documents/Wisdota/dota-analysis/web-server/download/src:/source:ro
    - /home/fischerq/Documents/Wisdota/dota-analysis/web-server/shared-code:/shared-code:ro
  links:
    - postgres:POSTGRES_IP