proxy:
  container_name: droplet-proxy
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /usr/local/dota-analysis/web-server/nginx/vhosts:/etc/nginx/vhost.d:ro
postgres:
  container_name: postgres-container
  image: postgres
  expose:
    - "5432"
  environment:
    POSTGRES_USER: "wisdota"
    POSTGRES_PASSWORD: "xxx"
    PGDATA: "/postgres/data"
  volumes:
    - /usr/local/dota-analysis/web-server/storage/postgres:/postgres
webserver:
  build: webserver
  expose:
    - "42000"
  volumes:
    - /usr/local/dota-analysis/web-server/webserver/src:/source:ro
    - /usr/local/dota-analysis/web-server/storage/webserver:/storage
    - /usr/local/dota-analysis/web-server/storage/shared:/shared
    - /usr/local/dota-analysis/web-server/files/webserver:/files:ro
  environment:
    VIRTUAL_HOST: "wisdota.com,www.wisdota.com"
    VIRTUAL_PORT: "42000"
    VERSION: "droplet"
  links:
    - postgres:POSTGRES_IP
analysis:
  build: analysis
  volumes:
    - /usr/local/dota-analysis/web-server/analysis/server-src:/source:ro
    - /usr/local/dota-analysis/web-server/analysis/extractor:/extractor:ro
    - /usr/local/dota-analysis/web-server/analysis/analysis:/analysis:ro

    - /usr/local/dota-analysis/web-server/storage/analysis:/storage
    - /usr/local/dota-analysis/web-server/storage/shared:/shared
    - /usr/local/dota-analysis/web-server/files/analysis:/files:ro
  links:
    - postgres:POSTGRES_IP
