proxy:
  container_name: droplet-proxy
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /usr/local/dota-analysis/web-server/nginx/vhosts:/etc/nginx/vhost.d:ro
postgres:
  container_name: postgres-container
  image: postgres
  expose:
    - "5432"
  ports:
    - "5432:5432"
  environment:
    POSTGRES_USER: "wisdota"
    POSTGRES_PASSWORD: "the-database-elephant"
    PGDATA: "/postgres/data"
  volumes:
    - /usr/local/dota-analysis/web-server/storage/postgres:/postgres
webserver:
  image: tembryo/wisdota-webserver
  expose:
    - "42000"
  volumes:
    - /usr/local/dota-analysis/web-server/storage/webserver:/storage
    - /usr/local/dota-analysis/web-server/storage/shared:/shared
  environment:
    VIRTUAL_HOST: "wisdota.com,www.wisdota.com"
    VIRTUAL_PORT: "42000"
    VERSION: "droplet"
  links:
    - postgres:POSTGRES_IP
scheduler:
  image: tembryo/wisdota-scheduler
  volumes:
    - /usr/local/dota-analysis/web-server/storage/scheduler:/storage
    - /usr/local/dota-analysis/web-server/storage/shared:/shared
  links:
    - postgres:POSTGRES_IP
analysis:
  image: tembryo/wisdota-analysis
  volumes:
    - /usr/local/dota-analysis/web-server/storage/analysis:/storage
    - /usr/local/dota-analysis/web-server/storage/shared:/shared
  links:
    - postgres:POSTGRES_IP
retrieve:
  image: tembryo/wisdota-retrieve
  volumes:
    - /usr/local/dota-analysis/web-server/storage/retrieve:/storage
    - /usr/local/dota-analysis/web-server/storage/shared:/shared
  links:
    - postgres:POSTGRES_IP
download:
  image: tembryo/wisdota-download
  volumes:
    - /usr/local/dota-analysis/web-server/storage/download:/storage
    - /usr/local/dota-analysis/web-server/storage/shared:/shared
  links:
    - postgres:POSTGRES_IP