database:
  container_name: database-container
  build: database
  volumes:
    - /usr/local/dota-analysis/web-server/storage/db:/data/db
  expose:
    - "42200"
webserver:
  build: webserver
  expose:
    - "42000"
  volumes:
    - /usr/local/dota-analysis/web-server/webserver/src:/source:ro
    - /usr/local/dota-analysis/web-server/storage/webserver:/storage
    - /usr/local/dota-analysis/web-server/files/webserver:/files:ro
  environment:
    VIRTUAL_HOST: tembryo.com
    VIRTUAL_PORT: 42000
  links:
    - database:DATABASE_IP
