proxy:
  container_name: wisdota-proxy
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /Users/richardmason/Documents/Github/Tembryo/dota-analysis/web-server/nginx/vhosts:/etc/nginx/vhost.d:ro
postgres:
  container_name: postgres-container
  image: postgres:9.4
  expose:
    - "5432"
  environment:
    POSTGRES_USER: "wisdota"
    POSTGRES_PASSWORD: "the-database-elephant"
    PGDATA: "/postgres/data"
  volumes:
    - /usr/local/tembryo-dev/postgres:/postgres
webserver:
  image: tembryo/wisdota-webserver
  expose:
    - "42000"
  volumes:
    - /usr/local/tembryo-dev/webserver:/storage
    - /usr/local/tembryo-dev/shared:/shared
    - /Users/richardmason/Documents/Github/Tembryo/dota-analysis/web-server/files/webserver:/files:ro
  environment:
    VERSION: "DEV"
    VIRTUAL_HOST: "192.168.99.100"
    VIRTUAL_PORT: "42000"
  links:
    - postgres:POSTGRES_IP
scheduler:
  image: tembryo/wisdota-scheduler
  volumes:
    - /usr/local/tembryo-dev/scheduler:/storage
    - /usr/local/tembryo-dev/shared:/shared
  environment:
    VERSION: "DEV"
  links:
    - postgres:POSTGRES_IP
analysis:
  image: tembryo/wisdota-analysis
  volumes:
    -  /usr/local/tembryo-dev/analysis:/storage
    - /usr/local/tembryo-dev/shared:/shared
    - /Users/richardmason/Documents/Github/Tembryo/dota-analysis/web-server/files/analysis:/files:ro
  environment:
    VERSION: "DEV"
  links:
    - postgres:POSTGRES_IP
retrieve:
  image: tembryo/wisdota-retrieve
  volumes:
    - /usr/local/tembryo-dev/retrieve:/storage
    - /usr/local/tembryo-dev/shared:/shared
  environment:
    VERSION: "DEV"
  links:
    - postgres:POSTGRES_IP
download:
  image: tembryo/wisdota-download
  volumes:
    - /usr/local/tembryo-dev/download:/storage
    - /usr/local/tembryo-dev/shared:/shared
  environment:
    VERSION: "DEV"
  links:
    - postgres:POSTGRES_IP
