postgres:
  image: postgres
  expose:
    - "5432"
  environment:
    POSTGRES_USER: "wisdota"
    POSTGRES_PASSWORD: "the-database-elephant"
    PGDATA: "/postgres/data"
  volumes:
    - /home/fischerq/Documents/Wisdota/dota-analysis/web-server/storage/postgres:/postgres
