learner:
  build: .
  volumes:
    - /home/fischerq/Documents/Wisdota/dota-analysis/ml-learn/src:/source:ro
    - /home/fischerq/Documents/Wisdota/dota-analysis/ml-data-crawler/files:/files-crawl
    - /home/fischerq/Documents/Wisdota/dota-analysis/ml-learn/analysis:/analysis
    - /home/fischerq/Documents/Wisdota/dota-analysis/replayAnalyser/Beta/event_extractor4.py:/analysis/analysis.py:ro
    - /home/fischerq/Documents/Wisdota/dota-analysis/dotaReplayProcessor/target/dotaReplayProcessor-0.0.1-SNAPSHOT.jar:/extract.jar:ro
    - /home/fischerq/Documents/Wisdota/dota-analysis/ml-learn/new_model:/files
    - /home/fischerq/Documents/Wisdota/dota-analysis/ml-learn/learn:/learn
