replay-fixer:
  build: .
  volumes:
    - /home/fischerq/Documents/Wisdota/dota-analysis/web-server/storage/shared:/shared
    - /home/fischerq/Documents/Wisdota/dota-analysis/replay-fixer/src:/source:ro
    - /home/fischerq/Documents/Wisdota/dota-analysis/web-server/shared-code:/shared-code:ro
  environment:
    VERSION: "DEV"
  external_links:
    - postgres-container:POSTGRES_IP